INSERT INTO tripulante (id_tripulante, nome_tripulante, estado_tripulante, criado_em, atualizado_em) VALUES
(1, 'Capitão Zorak', 'BEM', now(), now()),
(2, 'Tenente Quarx', 'FERIDO', now(), now()),
(3, 'Sargento Kralor', 'FERIDO', now(), now()),
(4, 'Engenheiro Kalix', 'FERIDO', now(), now()),
(5, 'Piloto Zylor', 'FOI_COM_DEUS', now(), now()),
(6, 'Oficial Ixan', 'FERIDO', now(), now()),
(7, 'Alferes Blor', 'FOI_COM_DEUS', now(), now()),
(8, 'Doutora Qendra', 'FERIDO', now(), now()),
(9, 'Comandante Ylora', 'FOI_COM_DEUS', now(), now()),
(10, 'Soldado Drax', 'FOI_COM_DEUS', now(), now()),
(11, 'Cientista Vlen', 'FOI_COM_DEUS', now(), now()),
(12, 'Técnico Xivor', 'FERIDO', now(), now()),
(13, 'Co-piloto Jzara', 'FERIDO', now(), now()),
(14, 'Oficial de Armas Barlok', 'FOI_COM_DEUS', now(), now()),
(15, 'Explorador Xarax', 'FERIDO', now(), now()),
(16, 'Chefe de Segurança Glynn', 'BEM', now(), now()),
(17, 'Navegador Rylak', 'FOI_COM_DEUS', now(), now()),
(18, 'Analista Xerk', 'BEM', now(), now()),
(19, 'Oficial de Comunicações Zyntar', 'FERIDO', now(), now()),
(20, 'Médico Nylar', 'FOI_COM_DEUS', now(), now()),
(21, 'Bióloga Yzma', 'FERIDO', now(), now()),
(22, 'Astrônoma Vlex', 'FERIDO', now(), now()),
(23, 'Engenheira Xarok', 'FOI_COM_DEUS', now(), now()),
(24, 'Técnico Xyvor', 'FERIDO', now(), now()),
(25, 'Oficial de Navegação Klorn', 'BEM', now(), now()),
(26, 'Capitã Zyra', 'FOI_COM_DEUS', now(), now()),
(27, 'Soldado Klor', 'BEM', now(), now()),
(28, 'Piloto Loran', 'FERIDO', now(), now()),
(29, 'Tenente Bryll', 'FERIDO', now(), now()),
(30, 'Mecânico Yzor', 'FERIDO', now(), now()),
(31, 'Oficial de Ciências Wylor', 'FOI_COM_DEUS', now(), now()),
(32, 'Coordenador Ixol', 'FERIDO', now(), now()),
(33, 'Segurança Grynn', 'BEM', now(), now()),
(34, 'Comunicador Zarok', 'FOI_COM_DEUS', now(), now()),
(35, 'Astrônomo Klyss', 'FOI_COM_DEUS', now(), now()),
(36, 'Tenente Vyra', 'BEM', now(), now()),
(37, 'Engenheiro Trask', 'FOI_COM_DEUS', now(), now()),
(38, 'Piloto Lyzar', 'FOI_COM_DEUS', now(), now()),
(39, 'Oficial Xebar', 'FERIDO', now(), now()),
(40, 'Alferes Krynx', 'FOI_COM_DEUS', now(), now()),
(41, 'Exploradora Vyxor', 'FERIDO', now(), now()),
(42, 'Oficial de Armas Blorn', 'FOI_COM_DEUS', now(), now()),
(43, 'Capitão Glymar', 'FOI_COM_DEUS', now(), now()),
(44, 'Biólogo Xylar', 'FOI_COM_DEUS', now(), now()),
(45, 'Chefe de Operações Vora', 'BEM', now(), now()),
(46, 'Cientista Tylor', 'FERIDO', now(), now()),
(47, 'Sargento Wrax', 'FERIDO', now(), now()),
(48, 'Engenheira Nylok', 'FERIDO', now(), now()),
(49, 'Piloto Xar', 'FOI_COM_DEUS', now(), now()),
(50, 'Oficial de Segurança Klyron', 'FERIDO', now(), now());
