INSERT INTO nave (
    nome,
    cor,
    local_queda,
    armamento,
    tipo_combustivel,
    grau_avaria,
    potencial_tecnologico,
    total_tripulante_bem,
    total_tripulante_ferido,
    total_tripulante_foi_com_deus,
    criado_em,
    atualizado_em
)
VALUES
    ('Nave Fênix', 'VERMELHA', 'OCEANO', 'LASER', 'PLASMA_DE_PLUTONIO', 'PERDA_TOTAL', 'DIVINA', 10, 5, 0, now(), now()),
    ('Estrela da Manhã', 'LARANJA', 'CONTINENTE', 'CANHAO_LAVA', 'GOTAS_DE_MATERIA_ESCURA', 'MUITO_DESTRUIDA', 'SOBERANA', 8, 2, 3, now(), now()),
    ('Vento Estelar', 'AZUL', 'SO_DEUS_SABE', 'SNIPER', 'LAGRIMAS_DE_UNICORNIO', 'PARCIALMENTE_DESTRUIDA', 'AVANCADA', 15, 1, 4, now(), now()),
    ('Dragão Cósmico', 'ANIL', 'OCEANO', 'RIFLE', 'ESPRESSO_QUANTICO', 'PRATICAMENTE_INTACTA', 'TRANSCENDENTE', 12, 0, 1, now(), now()),
    ('Sentinela Espacial', 'VERDE', 'CONTINENTE', 'BAZOOKA', 'PARTICULAS_VIRTUAIS', 'SEM_AVARIAS', 'PRIMITIVA', 7, 0, 0, now(), now()),
    ('Luz Celeste', 'VIOLETA', 'SO_DEUS_SABE', 'DEPLETED_URANIUM_MUNITION', 'FALHA_GRAVITACIONAL', 'MUITO_DESTRUIDA', 'SOBERANA', 9, 2, 5,now(), now()),
    ('Sombras do Espaço', 'COR_DESCONHECIDA', 'OCEANO', 'MACHINE_GUN', 'PLASMA_DE_PLUTONIO', 'PERDA_TOTAL', 'DIVINA', 5, 1, 3,now(), now()),
    ('Guardião da Galáxia', 'VERMELHA', 'CONTINENTE', 'PISTOL', 'GOTAS_DE_MATERIA_ESCURA', 'PARCIALMENTE_DESTRUIDA', 'AVANCADA', 13, 4, 1,now(), now()),
    ('Corvo Cósmico', 'AMARELA', 'SO_DEUS_SABE', 'SNIPER', 'LAGRIMAS_DE_UNICORNIO', 'SEM_AVARIAS', 'TRANSCENDENTE', 8, 0, 0,now(), now()),
    ('Meteoro Negro', 'AZUL', 'OCEANO', 'BLADE', 'ESPRESSO_QUANTICO', 'PERDA_TOTAL', 'DIVINA', 6, 2, 4,now(), now()),
    ('Lâmina Solar', 'VERDE', 'CONTINENTE', 'CANHAO_LAVA', 'PARTICULAS_VIRTUAIS', 'MUITO_DESTRUIDA', 'SOBERANA', 10, 1, 0,now(), now()),
    ('Brilho Estelar', 'ANIL', 'SO_DEUS_SABE', 'LASER', 'PLASMA_DE_PLUTONIO', 'PRATICAMENTE_INTACTA', 'AVANCADA', 9, 0, 1,now(), now()),
    ('Estrela Relâmpago', 'LARANJA', 'OCEANO', 'RIFLE', 'GOTAS_DE_MATERIA_ESCURA', 'SEM_AVARIAS', 'TRANSCENDENTE', 7, 0, 0,now(), now()),
    ('Chama Espacial', 'VIOLETA', 'CONTINENTE', 'SNIPER', 'FALHA_GRAVITACIONAL', 'MUITO_DESTRUIDA', 'PRIMITIVA', 14, 2, 2,now(), now()),
    ('Arco da Galáxia', 'COR_DESCONHECIDA', 'SO_DEUS_SABE', 'BAZOOKA', 'LAGRIMAS_DE_UNICORNIO', 'PERDA_TOTAL', 'DIVINA', 12, 3, 4,now(), now()),
    ('Vaga-lume Cósmico', 'VERMELHA', 'OCEANO', 'MACHINE_GUN', 'ESPRESSO_QUANTICO', 'PARCIALMENTE_DESTRUIDA', 'SOBERANA', 8, 1, 3,now(), now()),
    ('Pégaso Estelar', 'AMARELA', 'CONTINENTE', 'DEPLETED_URANIUM_MUNITION', 'PLASMA_DE_PLUTONIO', 'SEM_AVARIAS', 'AVANCADA', 13, 0, 0,now(), now()),
    ('Navio Fantasma', 'VERDE', 'SO_DEUS_SABE', 'TASER', 'PARTICULAS_VIRTUAIS', 'PERDA_TOTAL', 'DIVINA', 6, 3, 4,now(), now()),
    ('Cometa Azul', 'AZUL', 'OCEANO', 'SNIPER', 'FALHA_GRAVITACIONAL', 'MUITO_DESTRUIDA', 'TRANSCENDENTE', 7, 2, 1,now(), now()),
    ('Vapor da Nebulosa', 'ANIL', 'CONTINENTE', 'BOMB', 'GOTAS_DE_MATERIA_ESCURA', 'PRATICAMENTE_INTACTA', 'SOBERANA', 9, 1, 0,now(), now()),
    ('Sopro de Vênus', 'LARANJA', 'SO_DEUS_SABE', 'CANHAO_LAVA', 'LAGRIMAS_DE_UNICORNIO', 'PARCIALMENTE_DESTRUIDA', 'PRIMITIVA', 11, 3, 2,now(), now()),
    ('Dragão da Nebulosa', 'COR_DESCONHECIDA', 'OCEANO', 'PISTOL', 'PLASMA_DE_PLUTONIO', 'MUITO_DESTRUIDA', 'SOBERANA', 15, 1, 0,now(), now()),
    ('Relâmpago Estelar', 'VERMELHA', 'CONTINENTE', 'BLADE', 'ESPRESSO_QUANTICO', 'PERDA_TOTAL', 'AVANCADA', 5, 2, 3,now(), now()),
    ('Nevoeiro Galáctico', 'AMARELA', 'SO_DEUS_SABE', 'MACHINE_GUN', 'GOTAS_DE_MATERIA_ESCURA', 'PRATICAMENTE_INTACTA', 'DIVINA', 13, 0, 0,now(), now()),
    ('Pegasus Negro', 'ANIL', 'OCEANO', 'DEPLETED_URANIUM_MUNITION', 'PARTICULAS_VIRTUAIS', 'MUITO_DESTRUIDA', 'TRANSCENDENTE', 7, 3, 1,now(), now()),
    ('Lança da Estrela', 'VIOLETA', 'CONTINENTE', 'SNIPER', 'LAGRIMAS_DE_UNICORNIO', 'PARCIALMENTE_DESTRUIDA', 'SOBERANA', 10, 1, 4,now(), now()),
    ('Cavaleiro das Sombras', 'AZUL', 'SO_DEUS_SABE', 'BOMB', 'FALHA_GRAVITACIONAL', 'PERDA_TOTAL', 'DIVINA', 12, 2, 2,now(), now()),
    ('Chama da Noite', 'VERDE', 'OCEANO', 'RIFLE', 'PLASMA_DE_PLUTONIO', 'PRATICAMENTE_INTACTA', 'PRIMITIVA', 9, 0, 1,now(), now()),
    ('Rosa Estelar', 'LARANJA', 'CONTINENTE', 'TASER', 'ESPRESSO_QUANTICO', 'SEM_AVARIAS', 'TRANSCENDENTE', 6, 0, 0,now(), now()),
    ('Fogo da Galáxia', 'COR_DESCONHECIDA', 'SO_DEUS_SABE', 'LASER', 'GOTAS_DE_MATERIA_ESCURA', 'MUITO_DESTRUIDA', 'AVANCADA', 8, 1, 0, now(), now());

